version: '3.8'

services:
  dbt:
    build:
      context: . # Directory containing the Dockerfile
    container_name: dbt-container
    working_dir: /app
    volumes:
      - .:/app # Mount the current directory into the container
    environment:
      DBT_PROFILES_DIR: /app/profiles # Set the dbt profiles directory (adjust as needed)
    command: tail -f /dev/null
    restart: unless-stopped
